### ISSUE TITLE
trouble installing

### ISSUE THREAD

**Issue by demianrey** [ZBrettonYe/SSRPanel-OtakuMod#3]
**描述你遇到的bug**
简单的描述一下你遇到的bug

I did all the steps to the letter, I have experience installing these panels, but on two occasions I try it gives me error 500

**如何复现你的BUG**
为方便找bug，请说明你bug产生的步骤
Predis\Connection\ConnectionException thrown with message "Connection refused [tcp://127.0.0.1:6379]"

Stacktrace:
#60 Predis\Connection\ConnectionException in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/predis/predis/src/Connection/AbstractConnection.php:155
#59 Predis\Connection\AbstractConnection:onConnectionError in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/predis/predis/src/Connection/StreamConnection.php:128
#58 Predis\Connection\StreamConnection:createStreamSocket in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/predis/predis/src/Connection/StreamConnection.php:178
#57 Predis\Connection\StreamConnection:tcpStreamInitializer in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/predis/predis/src/Connection/StreamConnection.php:100
#56 Predis\Connection\StreamConnection:createResource in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/predis/predis/src/Connection/AbstractConnection.php:81
#55 Predis\Connection\AbstractConnection:connect in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/predis/predis/src/Connection/StreamConnection.php:258
#54 Predis\Connection\StreamConnection:connect in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/predis/predis/src/Connection/AbstractConnection.php:180
#53 Predis\Connection\AbstractConnection:getResource in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/predis/predis/src/Connection/StreamConnection.php:288
#52 Predis\Connection\StreamConnection:write in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/predis/predis/src/Connection/StreamConnection.php:394
#51 Predis\Connection\StreamConnection:writeRequest in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/predis/predis/src/Connection/AbstractConnection.php:110
#50 Predis\Connection\AbstractConnection:executeCommand in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/predis/predis/src/Client.php:331
#49 Predis\Client:executeCommand in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/predis/predis/src/Client.php:314
#48 Predis\Client:__call in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php:114
#47 Illuminate\Redis\Connections\Connection:command in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php:214
#46 Illuminate\Redis\Connections\Connection:__call in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Cache/RedisStore.php:54
#45 Illuminate\Cache\RedisStore:get in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Cache/Repository.php:97
#44 Illuminate\Cache\Repository:get in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Session/CacheBasedSessionHandler.php:58
#43 Illuminate\Session\CacheBasedSessionHandler:read in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Session/Store.php:97
#42 Illuminate\Session\Store:readFromHandler in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Session/Store.php:87
#41 Illuminate\Session\Store:loadSession in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Session/Store.php:71
#40 Illuminate\Session\Store:start in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:81
#39 Illuminate\Session\Middleware\StartSession:Illuminate\Session\Middleware\{closure} in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Support/helpers.php:1124
#38 tap in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:82
#37 Illuminate\Session\Middleware\StartSession:startSession in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:51
#36 Illuminate\Session\Middleware\StartSession:handle in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#35 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#34 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37
#33 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse:handle in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#32 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#31 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:66
#30 Illuminate\Cookie\Middleware\EncryptCookies:handle in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#29 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#28 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104
#27 Illuminate\Pipeline\Pipeline:then in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Routing/Router.php:682
#26 Illuminate\Routing\Router:runRouteWithinStack in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Routing/Router.php:657
#25 Illuminate\Routing\Router:runRoute in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Routing/Router.php:623
#24 Illuminate\Routing\Router:dispatchToRoute in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Routing/Router.php:612
#23 Illuminate\Routing\Router:dispatch in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:176
#22 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
#21 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php:65
#20 Barryvdh\Debugbar\Middleware\InjectDebugbar:handle in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#19 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#18 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/fideloper/proxy/src/TrustProxies.php:57
#17 Fideloper\Proxy\TrustProxies:handle in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#16 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#15 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21
#14 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#13 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#12 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21
#11 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#10 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#9 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27
#8 Illuminate\Foundation\Http\Middleware\ValidatePostSize:handle in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#7 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#6 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:62
#5 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode:handle in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#4 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#3 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104
#2 Illuminate\Pipeline\Pipeline:then in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:151
#1 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:116
#0 Illuminate\Foundation\Http\Kernel:handle in /www/wwwroot/demianred.tk/SSRPanel_OtakuMod/public/index.php:62

**截图**

![image](https://user-images.githubusercontent.com/48655207/79302816-02d54b00-7eb3-11ea-8df3-e539c439d8e4.png)
![image](https://user-images.githubusercontent.com/48655207/79302856-1da7bf80-7eb3-11ea-8292-11f9774eed60.png)

**Comment by ZBrettonYe** [comment]
u need to install Predis

**Comment by demianrey** [comment]
in the installation steps it does not say anything about predis, if it is necessary to install it?

**Comment by demianrey** [comment]
Hello again, I already installed redis and now the error is:
![IMG_20200420_142418_934](https://user-images.githubusercontent.com/48655207/79791641-4d235580-8313-11ea-832b-ea7dbd6e11cc.jpg)

**Comment by ZBrettonYe** [comment]
update your database

**Comment by demianrey** [comment]
I have to put each of the .sql files? or how can I update the database?

**Comment by ZBrettonYe** [comment]
I planed to add PayPal to payment system, but right now I have a hard time to  apply for develop account.

**Comment by demianrey** [comment]
if you like I can create a paypal developer account for you

It is my problem that I cannot edit user information? it gives me error 404

> I have to put each of the .sql files? or how can I update the database?
> edit: Now it works
> ![image](https://user-images.githubusercontent.com/48655207/79825607-17a45980-835f-11ea-98a9-03fa438097a3.png)
> 
> the view of this panel is more modern, excellent work.
> 
> P.S. Are you planning to integrate pay with paypal?
> 
> edit2: 404 error when editing user
> ![image](https://user-images.githubusercontent.com/48655207/79829369-7de1aa00-8368-11ea-94fa-edeab2c57ee4.png)

**Comment by ZBrettonYe** [comment]
This issue has been solved in the latest update

**Comment by demianrey** [comment]
can you tell me what command to use to update to the last modification without affecting

**Comment by ZBrettonYe** [comment]
sh update.sh
